version: "3.8"
services:
  sst-pg:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_database
    volumes:
      - sst-pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  sst-pg:
